//
// Created by wangrenxing on 2019-12-24.
//

#ifndef NEWBIEFFMPEG_COMMONERROR_H
#define NEWBIEFFMPEG_COMMONERROR_H

enum CommonError {
    ERR_OPEN_INPUT = 1,
    ERR_FIND_STREAM_INFO,
    ERR_FIND_DECODER,
    ERR_CODEC_ALLOC_CONTEXT,
    ERR_CODEC_OPEN,
    ERR_NOT_FIND_VIDEO_AND_AUDIO,

};
#endif //NEWBIEFFMPEG_COMMONERROR_H
